### ISSUE TITLE
inverse matrix

### ISSUE THREAD

**Issue by husfuu** [nicolaspanel/numjs#109]
Hello guys, do you know where can I get the inverse of matrix in numjs?

**Comment by nicolaspanel** [comment]
Hi
There is no such thing right now 
Maybe you should take a look to [mathjs](https://github.com/josdejong/mathjs)
best regards

**Comment by husfuu** [comment]
> Hi There is no such thing right now Maybe you should take a look to [mathjs](https://github.com/josdejong/mathjs) best regards

Thanks sir for the information
