### ISSUE TITLE
nj.identity is not a function

### ISSUE THREAD

**Issue by Spiruel** [nicolaspanel/numjs#18]
It's listed in the readme, but not in the documentation. I cannot get it to work. Does it exist? Thanks

**Comment by Spiruel** [comment]
Looks like the function is available in numjs.js but not numjs.min.js.

**Comment by nicolaspanel** [comment]
should be fixed now (numjs@0.14.2). can you confirm?

**Comment by Spiruel** [comment]
It is indeed fixed. Many thanks
