### ISSUE TITLE
nj.array with un-fixed shape

### ISSUE THREAD

**Issue by zixia** [nicolaspanel/numjs#22]
I do not know if sometimes the data array has the un-standarded shape, like the following code:

```js
const a = nj.array([0, [1, 2], [2, 3], [[4, [5, 6]]], 4])
console.log(a.shape) // Output: [ 5 ]
```

My question is: `a.shape` will be calculated only with the first-row element. 

Should I never use this kind of un-fixed shape?

A related TypeScript issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18508#issuecomment-318955303

**Comment by nicolaspanel** [comment]
since the  purpose of this lib is linear algebra, the shape has to be fixed (like it is in numpy)

**Comment by zixia** [comment]
Thanks, you are right.
