### ISSUE TITLE
Hello,Bro. I use "npm install numjs" in windows 7,node.js v6.11.3-32bit，npm report ERROR like that!

### ISSUE THREAD

**Issue by zhangshuiyong** [nicolaspanel/numjs#25]
npm ERR! argv "F:\\nodejs\\node.exe" "F:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "install" "numjs" "--save"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.17.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\nodequant\nodequant\npm-debug.log

**Comment by nicolaspanel** [comment]
Error is from [sharp](https://github.com/lovell/sharp) => see https://github.com/lovell/sharp/issues
