### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by arafeek** [nicolaspanel/numjs#29]
First off, thanks for all your work on this project!

I've been trying to use it in a ReactNative project as a numpy replacement for some TensorFlow preprocessing and I ran into a small issue with using the library outside of a NodeJS environment.

Specifically, the functions in `src/images/` have dependencies on the `path` module and `__dirname` variable which don't exist outside of node.

I was able to work around this by only conditionally exporting the images code at the bottom of  `src/index.js`.

I'd be happy to clean it up a bit and submit a PR if this is a use case you'd be interested in supporting. Cheers.

**Comment by nicolaspanel** [comment]
Thank you for your feedback 

numjs relies on browserify to produce a nodejs free version of the the code (available in `dist/numjs.min.js` or `dist/numjs.js`). Can you try to load the sources from there ?
