### ISSUE TITLE
Migrate to ES6

### ISSUE THREAD

**Issue by tryshchenko** [nicolaspanel/numjs#31]
Migration is quite simple, but it's possible to achieve a visually cleaner code as a result, especially when it comes to the functional programming. It's not critical - but I can take care of it.

I think it would simplify further development

**Comment by nicolaspanel** [comment]
I'm not sure it worth it since ES6 syntax will introduce incompatibility issue with older browsers or older versions of nodejs.
We may also add an additionnal compilation step (using babel) but I'm not sure it will work due to the use of browserify.
