### ISSUE TITLE
Convert to Array

### ISSUE THREAD

**Issue by fuzzthink** [nicolaspanel/numjs#35]
How do I convert array created to a JS Array?

thanks.

**Comment by nicolaspanel** [comment]
See NdArray#tolist() method

**Comment by fuzzthink** [comment]
It's not in the documentation at http://nicolaspanel.github.io/numjs/global.html . Is the page generated by a tool or manually? If manually, maybe add that to the repo so we can contribute to it.

**Comment by fuzzthink** [comment]
See it on the NdArray page. That link was on obvious on the global.html, so added it to README in pull #36
