### ISSUE TITLE
More closely mimic numpy API, WebAssembly

### ISSUE THREAD

**Issue by lastmjs** [nicolaspanel/numjs#38]
I'm on a quest to allow full on scientific computing in JavaScript, essentially to replace the need for Python source code. To achieve that, I imagine we'll need libraries that more closely mimic the APIs of popular Python libraries. Has this project considered more closely mimicking the numpy API, and how about WebAssembly? With WebAssembly we could potentially tap into the underlying libraries that numpy and others are built off of and get near-native capabilities in Node.js and the browser.

**Comment by nicolaspanel** [comment]
hi @lastmjs 
No, it hasn't been considered since I never used WebAssembly myself.  I tried Emscripten however and it was both painfull and inefficient (lead to very large builds)
