### ISSUE TITLE
Publish to unpkg.com?

### ISSUE THREAD

**Issue by vallis** [nicolaspanel/numjs#39]
Great package... would like to use it from observablehq.com. As far as I can tell, this requires the dist folder to be published on unpkg.com (the package is already there, but is incomplete). I don't know how that would be achieved.

Thanks!

**Comment by MartinKolarik** [comment]
You can import it from https://cdn.jsdelivr.net/gh/nicolaspanel/numjs@0.15.1/dist/numjs.min.js

**Comment by vallis** [comment]
Works, thanks!
