### ISSUE TITLE
console.log can not print the values

### ISSUE THREAD

**Issue by Honghe** [nicolaspanel/numjs#42]
env:
* Chrome 66

The doc says:
```
> var b = nj.array([[1,2,3], [4,5,6]]);
> b
array([[ 1, 2, 3],
       [ 4, 5, 6]])
```
but I can not print the values,
![image](https://user-images.githubusercontent.com/1092722/39010161-58c157a2-4440-11e8-8737-36dca1587011.png)

**Comment by anj-easyinspect** [comment]
I think you have to use the .toString()

`console.log(a.toString())`
