### ISSUE TITLE
Support for Uint8ClampedArray

### ISSUE THREAD

**Issue by eranimo** [nicolaspanel/numjs#5]
[Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray)

This would make numjs work well with [ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData), which is used for Javascript canvas data processing.

**Comment by nicolaspanel** [comment]
There is already an helper to work with canvas/images and it is called `nj.images.read`.
See [this tests](https://github.com/nicolaspanel/numjs/blob/master/test/karma/images.read.spec.js) for more info.

Let me know if it is what you were looking for.

Best regards
