### ISSUE TITLE
Question: browser support for sharp dependent features?

### ISSUE THREAD

**Issue by flekschas** [nicolaspanel/numjs#51]
This is a more a question out of curiosity: I notice your package relies on `sharp`, which is a package for image resizing written for Node.js. On the readme it says `numjs` runs in both: the browser and node.js. I am wondering which parts of `numjs` will work and which ones will fail when using `numjs` in the browser, assuming this statement is correct and that at least some part of sharp are incompatible https://github.com/lovell/sharp/issues/766#issuecomment-293378347.

Thanks for the clarification and thanks for developing `numjs`! :)

**Comment by nicolaspanel** [comment]
`numjs` uses [browserify](http://browserify.org/) to provide alternative implementation on the browser.
see https://github.com/nicolaspanel/numjs/blob/master/package.json#L89 for features mapping
