### ISSUE TITLE
Ones and zeros without shape

### ISSUE THREAD

**Issue by marcospgp** [nicolaspanel/numjs#53]
Allow creation of ones and zeros matrices that automatically set their shape based on the operations they are submitted to.

This way, I could stop having to do `const ones = nj.ones(x.shape);`

Edit: Since the reason this would be useful has mostly to do with elementwise operations, maybe an alternative to this would be providing a way to define custom elementwise operations, like the ones provided out of the box (such as `nj.sigmoid()`)

**Comment by nicolaspanel** [comment]
@marcospgp I'm not sure I understand the use case here. Does numpy has this kind of features ?

**Comment by marcospgp** [comment]
What numpy allows you to do is elementwise operations with the basic operators (*, /, +, -).

For example, calculating the elementwise inverse with numpy can be done with `1 / x`.
Meanwhile, with numjs you need something like `nj.ones(x.shape).divide(x)`.

Now we probably cannot override the operators in javascript in a safe way, so what we could do is to make `nj.ones` behave in a way that you could do `nj.ones.divide(x)`.

Alternatively, we could create a way to define elementwise operations such as `nj.elementwise(x, element => 1/element)`.

Perhaps both of these have certain applications that they resolve exclusively. Can you think of a use for the fancy version of `nj.ones` that couldn't be solved with `nj.elementwise()`?

**Comment by nicolaspanel** [comment]
> Now we probably cannot override the operators in javascript
Indeed we can't

 >  make nj.ones behave in a way that you could do nj.ones.divide(x).
Not sure it worth it

> we could create a way to define elementwise operations such as nj.elementwise(x, element => 1/element).
Do you know if numpy provide such feature ? It could be implemented easily using cwise

**Comment by marcospgp** [comment]
> Do you know if numpy provide such feature ? It could be implemented easily using cwise

I believe numpy doesn't need that kind of feature because you can simply do `1/matrix`

**Comment by nicolaspanel** [comment]
I mean, the ability to transform ND arrays elementwise through a custom function

**Comment by marcospgp** [comment]
https://stackoverflow.com/a/13556834/2037431

**Comment by marcospgp** [comment]
Tensorflow.js seems to have something like `tf.scalar(1)` which is more or less what we were discussing regarding `nj.ones`.
