### ISSUE TITLE
Creating a NdArray from ndarray

### ISSUE THREAD

**Issue by enobufs** [nicolaspanel/numjs#55]
This is a question.
I have a data (`nda` below) of type ndarray (scijs/ndarray). Its dtype is float32 and underlying storage (nda.data) is a Buffer.

I was able to convert ndarray to NdArray by doing this:

```js
const nja = nj.array(nda.data, 'float32').reshape(nda.shape);
``` 

I'd like to know if this is the right way to do.  Would it allocate a new buffer under the hood?
(Some documents about migrating from ndarray to numjs(NdArray) would be great.)

Thanks in advance.

**Comment by enobufs** [comment]
I noticed, NdArray#selection is actually an scijs/ndarray. The NdArray's constructor takes the first argument as an 'selection'.  I believe the following is the answer:

```js
const nja = nj.NdArray(nda);
```

Correct?

**Comment by nicolaspanel** [comment]
sorry for the delay
[`clone` method](https://github.com/nicolaspanel/numjs/blob/master/src/ndarray.js#L698) implementation should answer your question
Best regards
