### ISSUE TITLE
Diagonal / identity matrices

### ISSUE THREAD

**Issue by martinruenz** [nicolaspanel/numjs#8]
What is the standard way to create diagonal matrices or identity matrices?

I searched the source very quickly and couldn't find something promising. An example in the readme would be nice.

**Comment by nicolaspanel** [comment]
@martinruenz : both `nj.diag` and `nj.identity` are now available (numjs@0.12.0)
see readme for more info

**Comment by martinruenz** [comment]
Superb! Thanks!
