### ISSUE TITLE
`.equal()` changes array to unexpected values

### ISSUE THREAD

**Issue by GalvinGao** [nicolaspanel/numjs#88]
- Using `numjs`: `0.16.0`
- Minimal Reproducible Demo: https://codesandbox.io/s/sleepy-wu-kp6i3?file=/src/index.js

## Expected
The `.equal()` method shall NOT change the arrays supplied or, otherwise state explicitly in documentation

## Current Behavior
The `.equal()` method changes all values in the first array supplied to the comparing result.

**Comment by nicolaspanel** [comment]
fixed in v0.16.1
